/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZasadyCookiesRouteImport } from './routes/zasady-cookies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProvereniVozidlaRouteImport } from './routes/provereni-vozidla'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as ObchodniPodminkyRouteImport } from './routes/obchodni-podminky'
import { Route as OMneRouteImport } from './routes/o-mne'
import { Route as DuveraABezpecnostRouteImport } from './routes/duvera-a-bezpecnost'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedKlientRouteImport } from './routes/_authenticated/klient'

const ZasadyCookiesRoute = ZasadyCookiesRouteImport.update({
  id: '/zasady-cookies',
  path: '/zasady-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvereniVozidlaRoute = ProvereniVozidlaRouteImport.update({
  id: '/provereni-vozidla',
  path: '/provereni-vozidla',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodniPodminkyRoute = ObchodniPodminkyRouteImport.update({
  id: '/obchodni-podminky',
  path: '/obchodni-podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const OMneRoute = OMneRouteImport.update({
  id: '/o-mne',
  path: '/o-mne',
  getParentRoute: () => rootRouteImport,
} as any)
const DuveraABezpecnostRoute = DuveraABezpecnostRouteImport.update({
  id: '/duvera-a-bezpecnost',
  path: '/duvera-a-bezpecnost',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedKlientRoute = AuthenticatedKlientRouteImport.update({
  id: '/klient',
  path: '/klient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/duvera-a-bezpecnost': typeof DuveraABezpecnostRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/provereni-vozidla': typeof ProvereniVozidlaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zasady-cookies': typeof ZasadyCookiesRoute
  '/klient': typeof AuthenticatedKlientRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duvera-a-bezpecnost': typeof DuveraABezpecnostRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/provereni-vozidla': typeof ProvereniVozidlaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zasady-cookies': typeof ZasadyCookiesRoute
  '/klient': typeof AuthenticatedKlientRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/duvera-a-bezpecnost': typeof DuveraABezpecnostRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/provereni-vozidla': typeof ProvereniVozidlaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zasady-cookies': typeof ZasadyCookiesRoute
  '/_authenticated/klient': typeof AuthenticatedKlientRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/duvera-a-bezpecnost'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/provereni-vozidla'
    | '/sitemap.xml'
    | '/zasady-cookies'
    | '/klient'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/duvera-a-bezpecnost'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/provereni-vozidla'
    | '/sitemap.xml'
    | '/zasady-cookies'
    | '/klient'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/duvera-a-bezpecnost'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/provereni-vozidla'
    | '/sitemap.xml'
    | '/zasady-cookies'
    | '/_authenticated/klient'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  DuveraABezpecnostRoute: typeof DuveraABezpecnostRoute
  OMneRoute: typeof OMneRoute
  ObchodniPodminkyRoute: typeof ObchodniPodminkyRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  ProvereniVozidlaRoute: typeof ProvereniVozidlaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZasadyCookiesRoute: typeof ZasadyCookiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zasady-cookies': {
      id: '/zasady-cookies'
      path: '/zasady-cookies'
      fullPath: '/zasady-cookies'
      preLoaderRoute: typeof ZasadyCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provereni-vozidla': {
      id: '/provereni-vozidla'
      path: '/provereni-vozidla'
      fullPath: '/provereni-vozidla'
      preLoaderRoute: typeof ProvereniVozidlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodni-podminky': {
      id: '/obchodni-podminky'
      path: '/obchodni-podminky'
      fullPath: '/obchodni-podminky'
      preLoaderRoute: typeof ObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mne': {
      id: '/o-mne'
      path: '/o-mne'
      fullPath: '/o-mne'
      preLoaderRoute: typeof OMneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvera-a-bezpecnost': {
      id: '/duvera-a-bezpecnost'
      path: '/duvera-a-bezpecnost'
      fullPath: '/duvera-a-bezpecnost'
      preLoaderRoute: typeof DuveraABezpecnostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/klient': {
      id: '/_authenticated/klient'
      path: '/klient'
      fullPath: '/klient'
      preLoaderRoute: typeof AuthenticatedKlientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKlientRoute: typeof AuthenticatedKlientRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKlientRoute: AuthenticatedKlientRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  DuveraABezpecnostRoute: DuveraABezpecnostRoute,
  OMneRoute: OMneRoute,
  ObchodniPodminkyRoute: ObchodniPodminkyRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  ProvereniVozidlaRoute: ProvereniVozidlaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZasadyCookiesRoute: ZasadyCookiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
